#!/usr/bin/env node
import { spawn } from 'node:child_process'
import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

function usage(): string {
  return `Usage: dsh-with-chatgpt standalone [options]\n\nOptions:\n  --host <host>             standalone UI bind host (default: 127.0.0.1)\n  --port <port>             standalone UI port (default: 3460; 0 = random)\n  --daemon-mode <mode>      Agent Helm daemon mode: auto, external, or managed (default: auto)\n  --daemon-socket <path>    Agent Helm daemon socket (default: Core config)\n  --adapter-id <id>         unique DSH adapter id (default: dsh-standalone)\n  -h, --help                show help\n`
}

function parseArgs(argv: string[]): {
  command?: string
  host: string
  port: number
  daemonMode: 'auto' | 'external' | 'managed'
  daemonSocket: string
  adapterId: string
  help: boolean
} {
  const args = [...argv]
  const command = args.shift()
  let host = '127.0.0.1'
  let port = 3460
  let daemonMode: 'auto' | 'external' | 'managed' = 'auto'
  let daemonSocket = ''
  let adapterId = 'dsh-standalone'
  let help = false
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index]
    if (arg === '-h' || arg === '--help') { help = true; continue }
    if (arg === '--host') { host = args[++index] ?? ''; if (!host) throw new Error('--host requires a value'); continue }
    if (arg === '--port') {
      const raw = args[++index]
      port = Number(raw)
      if (!Number.isInteger(port) || port < 0 || port > 65535) throw new Error('--port must be an integer from 0 to 65535')
      continue
    }
    if (arg === '--daemon-mode') {
      const value = args[++index]
      if (value !== 'auto' && value !== 'external' && value !== 'managed') throw new Error('--daemon-mode must be auto, external, or managed')
      daemonMode = value
      continue
    }
    if (arg === '--daemon-socket') {
      daemonSocket = args[++index] ?? ''
      if (!daemonSocket) throw new Error('--daemon-socket requires a value')
      continue
    }
    if (arg === '--adapter-id') {
      adapterId = (args[++index] ?? '').trim()
      if (!adapterId) throw new Error('--adapter-id requires a value')
      continue
    }
    throw new Error(`unknown option: ${arg}`)
  }
  return { ...(command ? { command } : {}), host, port, daemonMode, daemonSocket, adapterId, help }
}

function standalonePluginUrl(): string {
  return pathToFileURL(fileURLToPath(new URL('./standalone-host.js', import.meta.url))).href
}

function yamlString(value: string): string {
  return JSON.stringify(value)
}

async function runStandalone(
  host: string,
  port: number,
  daemonMode: 'auto' | 'external' | 'managed',
  daemonSocket: string,
  adapterId: string,
): Promise<number> {
  const temp = await mkdtemp(join(tmpdir(), 'dsh-with-chatgpt-standalone-'))
  const patch = join(temp, 'standalone.patch.yml')
  const plugin = standalonePluginUrl()
  const source = `# Generated by dsh-with-chatgpt standalone.\n- id: headless-startup\n  disabled: true\n\n- id: headless-runner\n  disabled: true\n\n- insert:\n  - id: standalone-storage\n    name: '@deepseek-ai/dsh-storage'\n\n  - id: standalone-storage-json\n    name: '@deepseek-ai/dsh-storage-json'\n    config:\n      root: !!js dshHomePath('storages')\n\n  - id: standalone-storage-domain\n    name: '@deepseek-ai/dsh-storage-domain'\n    config:\n      backend: json\n\n  - id: dsh-with-chatgpt-standalone\n    name: ${yamlString(plugin)}\n    config:\n      daemonMode: ${yamlString(daemonMode)}\n      daemonSocket: ${yamlString(daemonSocket)}\n      adapterId: ${yamlString(adapterId)}\n      host: 127.0.0.1\n      port: 3457\n      tokenFile: ''\n      tokenEnv: AGENT_HELM_TOKEN\n      tunnelEnabled: true\n      tunnelIdEnv: CONTROL_PLANE_TUNNEL_ID\n      tunnelApiKeyEnv: CONTROL_PLANE_API_KEY\n      tunnelProxyEnv: HTTPS_PROXY\n      tunnelPollTimeoutMs: 30000\n      tunnelPollDeadlineGuardrailMs: 3000\n      tunnelHealthListenAddr: 127.0.0.1:3458\n      standaloneHost: ${yamlString(host)}\n      standalonePort: ${String(port)}\n`
  await writeFile(patch, source)
  try {
    const child = spawn('dsh', ['--profile', 'headless', '--patch', patch], {
      cwd: process.cwd(),
      env: process.env,
      stdio: 'inherit',
    })
    const forward = (signal: NodeJS.Signals) => { if (child.exitCode === null) child.kill(signal) }
    process.once('SIGINT', forward)
    process.once('SIGTERM', forward)
    return await new Promise<number>((resolve, reject) => {
      child.once('error', reject)
      child.once('exit', (code, signal) => resolve(code ?? (signal ? 1 : 0)))
    })
  } finally {
    await rm(temp, { recursive: true, force: true })
  }
}

try {
  const parsed = parseArgs(process.argv.slice(2))
  if (parsed.help || !parsed.command) {
    process.stdout.write(usage())
    process.exitCode = parsed.command ? 0 : 1
  } else if (parsed.command !== 'standalone') {
    process.stderr.write(`Unknown command: ${parsed.command}\n\n${usage()}`)
    process.exitCode = 1
  } else {
    process.exitCode = await runStandalone(parsed.host, parsed.port, parsed.daemonMode, parsed.daemonSocket, parsed.adapterId)
  }
} catch (error) {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
  process.exitCode = 1
}
